# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-08 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('is_delete', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20)),
                ('gpic', models.ImageField(upload_to='df_goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_delete', models.BooleanField(default=False)),
                ('gunit', models.CharField(max_length=20)),
                ('gclick', models.IntegerField()),
                ('gintro', models.CharField(max_length=200)),
                ('ginventory', models.IntegerField()),
                ('gcontent', tinymce.models.HTMLField()),
                ('gadv', models.BooleanField(default=False)),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodCategory')),
            ],
        ),
    ]
