# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-08 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uaddress',
            field=models.CharField(default='', max_length=100, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uphone',
            field=models.CharField(default='', max_length=15, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='upostcode',
            field=models.CharField(default='', max_length=8, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ushouhuo',
            field=models.CharField(default='', max_length=20, verbose_name='收货人'),
        ),
    ]
